services:
  mongo:
    image: mongo:7.0-jammy
    ports:
      - "27017:27017"
    networks: # adding network
      - marsai-network
    volumes:
      - mongo-data:/data/db
    restart: on-failure
  
  marsai-app:
    container_name: marsai-app-container
    build:
      context: .
    volumes:
      - ./db.json:/app/db.json
    ports:
      - "3000:3000"
    networks:
      - marsai-network
    env_file:
      - ./.env
    restart: on-failure
    depends_on:
      - mongo

networks:
  marsai-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local