services:
  mongo:
    image: mongo:7.0-jammy
    ports:
      - "27017:27017"
    networks:
      - marsai-network
    volumes:
      - mongo-data:/data/db
    restart: on-failure
  
  marsai-app:
    container_name: marsai-app-container
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - marsai-network
    environment:
      - BOT_TOKEN=8002864227:AAEXEploUo89MeuyYiUxcFv4aCW3tosfd_k
      - RPC_TOKEN=lShJFo-23_TfZrrZWaTQT-j7V9b67UfG
      - PORT=3000
      - NODE_ENV=development
    restart: on-failure
    depends_on:
      - mongo

networks:
  marsai-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local